spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-today-drink.cok2ernv7ujp.us-east-2.rds.amazonaws.com:5432/drink
    username: today_drink
    password: todaydrink123
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      platform: postgres

jwt:
  header : Authorization
  secret : dG9kYXlkcmluay1qd3Qtc2VjcmV0LXRvZGF5ZHJpbmstand0LXNlY3JldC10b2RheWRyaW5rLWp3dC1zZWNyZXQ=
  token-validity-in-seconds : 86400